apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: mycluster
  region: ap-south-1
nodeGroups:
  - name: ng1
    desiredCapacity: 3
    instanceType: t2.micro
    ssh:
      publicKeyName: mykey
  - name: ng2
    desiredCapacity: 2
    instanceType: t2.small
    ssh:
      publicKeyName: mykey
