apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-pass
    literals:
      - password=redhat
resources:
  - create-storage.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
